[package]
name = "neweden"
version = "0.1.0"
authors = ["David Soria Parra <dsp@experimentalworks.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
database = ["diesel"]

[dependencies]
anyhow = "*"
thiserror = "*"
diesel = { version = "*", optional = true, features = ["postgres"] }
pathfinding = "*"