[package]
name = "neweden"
version = "0.1.2"
authors = ["David Soria Parra <dsp@experimentalworks.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
database = ["diesel"]
rpc_types = ["rpc"]

[dependencies]
anyhow = "*"
diesel = { version = "*", optional = true, features = ["postgres"] }
rpc = { path = "../rpc", optional = true }
pathfinding = "*"
rstar = "*"
thiserror = "*"
